sonar.projectKey=aembit_edge_sdks_py
sonar.projectName=Edge SDK (Python)
sonar.organization=aembit
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/dist/**,**/.pkg-venv/**,**/examples/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10, 3.11, 3.12, 3.13
