sonar.projectKey=aembit_edge_sdks_py
sonar.organization=aembit
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/dist/**,**/.pkg-venv/**,**/examples/**
sonar.python.coverage.reportPaths=coverage.xml
