sonar.projectKey=aembit_edge_sdks_ts
sonar.organization=aembit
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/examples/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
